### ISSUE TITLE
jpterm fails when reading from stdin

### ISSUE THREAD

**Issue by mattiasb** [jmespath-community/jmespath.terminal#14]
Piping some simple JSON like `[]` to `jpterm` fails like this:

```console
$ echo '[]' | jpterm
Traceback (most recent call last):
  File "/home/mattiasb/.local/bin/jpterm", line 6, in <module>
    jpterm.main()
  File "/home/mattiasb/.local/pipx/venvs/jmespath-community-terminal/lib64/python3.12/site-packages/jpterm.py", line 231, in main
    display.main(screen=screen)
  File "/home/mattiasb/.local/pipx/venvs/jmespath-community-terminal/lib64/python3.12/site-packages/jpterm.py", line 148, in main
    self.loop.run()
  File "/home/mattiasb/.local/pipx/venvs/jmespath-community-terminal/lib64/python3.12/site-packages/urwid/main_loop.py", line 287, in run
    self._run()
  File "/home/mattiasb/.local/pipx/venvs/jmespath-community-terminal/lib64/python3.12/site-packages/urwid/main_loop.py", line 385, in _run
    self.event_loop.run()
  File "/home/mattiasb/.local/pipx/venvs/jmespath-community-terminal/lib64/python3.12/site-packages/urwid/main_loop.py", line 790, in run
    self._loop()
  File "/home/mattiasb/.local/pipx/venvs/jmespath-community-terminal/lib64/python3.12/site-packages/urwid/main_loop.py", line 827, in _loop
    self._watch_files[fd]()
  File "/home/mattiasb/.local/pipx/venvs/jmespath-community-terminal/lib64/python3.12/site-packages/urwid/raw_display.py", line 417, in <lambda>
    event_loop, callback, self.get_available_raw_input())
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mattiasb/.local/pipx/venvs/jmespath-community-terminal/lib64/python3.12/site-packages/urwid/raw_display.py", line 449, in get_available_raw_input
    codes = self._get_gpm_codes() + self._get_keyboard_codes()
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mattiasb/.local/pipx/venvs/jmespath-community-terminal/lib64/python3.12/site-packages/urwid/raw_display.py", line 523, in _get_keyboard_codes
    code = self._getch_nodelay()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/mattiasb/.local/pipx/venvs/jmespath-community-terminal/lib64/python3.12/site-packages/urwid/raw_display.py", line 661, in _getch_nodelay
    return self._getch(0)
           ^^^^^^^^^^^^^^
  File "/home/mattiasb/.local/pipx/venvs/jmespath-community-terminal/lib64/python3.12/site-packages/urwid/raw_display.py", line 571, in _getch
    return ord(os.read(fd, 1))
           ^^^^^^^^^^^^^^^^^^^
TypeError: ord() expected a character, but string of length 0 found
```

This was supposedly fixed by https://github.com/jmespath-community/jmespath.terminal/pull/4 but it seems it was not enough.

## How to reproduce

To make sure this wasn't something weird on my machine I reproduced
it in a fresh Ubuntu 24.04 container. Swap `podman` for `docker` if you
prefer. It should work the same.

```console
$ podman run --rm -it                                              \
       --env DEBIAN_FRONTEND=noninteractive                        \
       --env PATH='/root/.local/bin:/usr/sbin:/usr/bin:/sbin:/bin' \
       docker.io/ubuntu:24.04                                      \
       /bin/bash -c " apt update                                   \
                    ; apt upgrade -y                               \
                    ; apt install -y python-is-python3 pipx        \
                    ; pipx install jmespath-community-terminal     \
                    ; echo '[]' | jpterm                           \
                    "

```

**Comment by kit494way** [comment]
The [fix](https://github.com/jmespath-community/jmespath.terminal/pull/4) has not yet been released.
Try installing from the repository.
```sh
pipx install git+https://github.com/jmespath-community/jmespath.terminal.git
```
